{{ if Values.gui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "debezium-ui.labels" . | nindent 4 }}
  labels:
    {{- include "debezium-ui.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      labels: 
        {{- include "debezium-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- if not .Values.gui.autoScaling.enabled -}}
      replicas: {{ .Values.gui.replicaCount }}
      imagePullSecrests:
      containers:
      - image: "{{ .Values.gui.image.registry }}/{{ .Values.gui.image.name }}:{{ .Values.gui.image.tag }}"
        name: debezium-ui
        resources:
          {{- toYaml .Values.gui.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
{{- end }}